name: deploy tst

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17

      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install android

      - name: Restore dependencies
        run: dotnet restore Quiz/Quiz.csproj

      - name: Build app binary
        run: dotnet build Quiz/Quiz.csproj --configuration Release --framework net7.0-android --no-restore

      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: quiz.apk
          path: Quiz/bin/Release/net7.0-android/*.apk
